# Estructuras condicionales y uso de hostvar
# By Ed Scrimaglia
# hostvar, es un diccionario global donde Ansible guarda las variables de cada host del inventario… incluso localhost.
# Ansible compone hostvars antes de que empiece cada play, y set_fact pega esas variables en el mapa general del host.


---
- name: Playbook definicion de variables
  hosts: localhost
  gather_facts: false

  vars_files:
    - ./modelo_datos/modelo_datos.yaml

  tasks:
    - name: Definicion de variables
      ansible.builtin.set_fact:
        version: "{{ modelo.metadatos.version }}"
        autor: "{{ modelo.metadatos.autor }}"
        fecha_de_creacion: "{{ modelo.metadatos.fecha_creacion }}"
        zona_horaria: "{{ modelo.metadatos.time_zone }}"

- name: Condicionales usando variables definidas
  hosts: cisco_ios
  gather_facts: false

  tasks:
    - name: Mostrar version del proyecto
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
      register: salida_version
# Ejecutá esta tarea solo si la variable version que está definida en el host localhost vale 1.0
# Es un puente entre plays el segundo play consulta variables generadas en el primero.
      when: hostvars['localhost'].version == '1.0'

    - name: Mostrar informacion del dispositivo actual
      ansible.builtin.debug:
        var: salida_version.stdout_lines
      when: hostvars['localhost'].version == '1.0'