[project]
name = "ejemplo2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible-pylibssh>=1.3.0",
    "jsonschema>=4.25.1",
    "netmiko>=4.6.0",
    "paramiko>=4.0.0",
    "scp>=0.15.0",
]
